name: GPTrivia
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - anyio=3.5.0
  - async-timeout=4.0.3
  - attrs=23.1.0
  - backports=1.1
  - backports.zoneinfo=0.2.1
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - ca-certificates=2023.12.12
  - cachetools=4.2.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.7
  - distro=1.8.0
  - django=4.1
  - django-cors-headers=4.3.1
  - djangorestframework=3.14.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - giflib=5.2.1
  - google-api-core=2.10.1
  - google-api-python-client=2.111.0
  - google-auth=2.22.0
  - google-auth-httplib2=0.2.0
  - google-auth-oauthlib=0.5.2
  - googleapis-common-protos=1.56.4
  - h11=0.12.0
  - h2=4.0.0
  - hpack=4.0.0
  - httpcore=0.15.0
  - httplib2=0.22.0
  - httpx=0.23.0
  - hyperframe=6.0.1
  - idna=3.4
  - jpeg=9e
  - jsonfield=3.1.0
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - multidict=6.0.4
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openai=1.3.6
  - openjpeg=2.3.0
  - openssl=3.0.12
  - pandas=2.0.3
  - pandas-stubs=1.5.3.230203
  - pillow=10.0.1
  - pip=23.3.1
  - protobuf=3.20.3
  - psycopg2=2.9.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=1.10.12
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rfc3986=1.4.0
  - rsa=4.7.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - tk=8.6.12
  - tqdm=4.65.0
  - types-pytz=2022.4.0.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uritemplate=4.1.1
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yarl=1.9.3
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asgiref==3.7.2
      - channels==4.0.0
      - diskcache==5.6.3
      - flaml==2.1.1
      - joblib==1.4.2
      - pyautogen==0.2.2
      - python-dotenv==1.0.0
      - regex==2023.12.25
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tiktoken==0.5.2