name: myenv
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - zstd=1.5.2  # Change version if 1.5.5 is unavailable
  - zlib=1.2.11  # Change version if 1.2.13 is unavailable
  - yarl
  - xz
  - wheel
  - urllib3
  - typing_extensions
  - tqdm
  - tk
  - sqlparse
  - sqlite
  - sniffio
  - setuptools
  - requests
  - readline
  - pytz
  - python=3.8
  - pysocks
  - pyparsing
  - pyopenssl
  - pyjwt
  - pydantic
  - psycopg2
  - protobuf
  - pip
  - pillow
  - pandas-stubs
  - pandas
  - openssl
  - openjpeg
  - openai
  - oauthlib
  - numpy-base
  - numpy
  - numexpr
  - ncurses
  - multidict
  - lz4-c
  - llvm-openmp
  - libwebp-base
  - libwebp
  - libtiff
  - libprotobuf
  - libpq
  - libpng
  - libopenblas
  - libgfortran5
  - libgfortran
  - libffi
  - libedit
  - libdeflate
  - libcxx
  - lerc
  - lcms2
  - krb5
  - jpeg
  - idna
  - httpx
  - httpcore
  - h2
  - googleapis-common-protos
  - google-auth-oauthlib
  - google-auth
  - google-api-core
  - giflib
  - frozenlist
  - freetype
  - django
  - distro
  - cryptography
  - click
  - cffi
  - certifi
  - ca-certificates
  - brotli-python
  - bottleneck
  - blinker
  - backports.zoneinfo
  - attrs
  - async-timeout
  - anyio
  - aiohttp