# Generated by Django 4.1.7 on 2023-03-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTriviaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('major_category', models.CharField(max_length=100)),
                ('minor_category1', models.CharField(max_length=100)),
                ('minor_category2', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('round_number', models.IntegerField()),
                ('max_score', models.FloatField(null=True)),
                ('score_alex', models.FloatField(null=True)),
                ('score_ichigo', models.FloatField(null=True)),
                ('score_megan', models.FloatField(null=True)),
                ('score_zach', models.FloatField(null=True)),
                ('score_jenny', models.FloatField(null=True)),
                ('score_debi', models.FloatField(null=True)),
                ('score_dan', models.FloatField(null=True)),
                ('score_chris', models.FloatField(null=True)),
                ('score_drew', models.FloatField(null=True)),
            ],
        ),
    ]
