# Generated by Django 4.1.7 on 2023-05-03 04:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTriviaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('major_category', models.CharField(max_length=100)),
                ('minor_category1', models.CharField(max_length=100)),
                ('minor_category2', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('round_number', models.IntegerField()),
                ('max_score', models.FloatField(null=True)),
                ('score_alex', models.FloatField(null=True)),
                ('score_ichigo', models.FloatField(null=True)),
                ('score_megan', models.FloatField(null=True)),
                ('score_zach', models.FloatField(null=True)),
                ('score_jenny', models.FloatField(null=True)),
                ('score_debi', models.FloatField(null=True)),
                ('score_dan', models.FloatField(null=True)),
                ('score_chris', models.FloatField(null=True)),
                ('score_drew', models.FloatField(null=True)),
                ('score_jeff', models.FloatField(null=True)),
                ('score_dillon', models.FloatField(null=True)),
                ('score_paige', models.FloatField(null=True)),
                ('replay', models.BooleanField(default=False)),
                ('cooperative', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, default='https://docs.google.com/presentation/d/1gC9DR9TmQK_9ls8Npw8Sc99qKI6YN9nRqLuVj0W07ns/embed?start=false&slide=id.g717c8ec4cb_2_0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MergedPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('presentation_id', models.CharField(max_length=255)),
                ('round_names', jsonfield.fields.JSONField(default=list)),
                ('creator_list', jsonfield.fields.JSONField(default=list)),
                ('joker_round_indices', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
