# Generated by Django 4.1.7 on 2023-04-18 16:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('presentation_id', models.CharField(max_length=255)),
                ('round_names', jsonfield.fields.JSONField(default=list)),
                ('creator_list', jsonfield.fields.JSONField(default=list)),
            ],
        ),
    ]
