# Generated by Django 4.1.7 on 2023-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0002_mergedpresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptriviaround',
            name='joker_round_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
