# Generated by Django 4.1 on 2024-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GPTrivia", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptriviaround",
            name="score_tom",
            field=models.FloatField(null=True),
        ),
    ]
