# Generated by Django 4.1.7 on 2023-04-28 19:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0003_gptriviaround_joker_round_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptriviaround',
            name='joker_round_index',
        ),
        migrations.AddField(
            model_name='mergedpresentation',
            name='joker_round_indices',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
