# Generated by Django 4.1 on 2024-02-13 19:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("GPTrivia", "0004_gptriviaround_score_tom"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedpresentation",
            name="host",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="mergedpresentation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mergedpresentation",
            name="player_list",
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mergedpresentation",
            name="scorekeeper",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="mergedpresentation",
            name="style_points",
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mergedpresentation",
            name="tiebreak_winner",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
