# Generated by Django 4.1.7 on 2023-05-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0004_remove_gptriviaround_joker_round_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptriviaround',
            name='cooperative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gptriviaround',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gptriviaround',
            name='replay',
            field=models.BooleanField(default=False),
        ),
    ]
