# Generated by Django 4.1.7 on 2023-05-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0006_gptriviaround_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptriviaround',
            name='link',
            field=models.CharField(blank=True, default='https://docs.google.com/presentation/d/1gC9DR9TmQK_9ls8Npw8Sc99qKI6YN9nRqLuVj0W07ns/embed?start=false&slide=id.g717c8ec4cb_2_0', max_length=255),
        ),
    ]
