# Generated by Django 4.2.15 on 2024-11-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GPTrivia", "0008_jeopardyround_jeopardyquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="jeopardyround",
            name="type",
            field=models.CharField(
                choices=[
                    ("JEOPARDY", "Jeopardy"),
                    ("DOUBLE_JEOPARDY", "Double Jeopardy"),
                    ("FINAL_JEOPARDY", "Final Jeopardy"),
                ],
                default="JEOPARDY",
                max_length=20,
            ),
        ),
    ]
