# Generated by Django 4.2.15 on 2024-11-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GPTrivia", "0009_jeopardyround_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jeopardyquestion",
            name="daily_double",
            field=models.BooleanField(default=False),
        ),
    ]
