# Generated by Django 4.1.7 on 2026-03-21 00:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0026_gpviaround_secondary_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundQuestionAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('round_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('source_presentation_id', models.CharField(blank=True, default='', max_length=255)),
                ('source_slide_range', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analysis_runs', to='GPTrivia.gptriviaround')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoundQuestionAnalysisEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=150)),
                ('round_date', models.DateField(blank=True, null=True)),
                ('question_number', models.IntegerField(default=1)),
                ('question_text', models.TextField(blank=True, default='')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('round_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('major_category', models.CharField(blank=True, default='', max_length=100)),
                ('minor_category1', models.CharField(blank=True, default='', max_length=100)),
                ('minor_category2', models.CharField(blank=True, default='', max_length=100)),
                ('player_correctness', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analysis_entries', to='GPTrivia.gptriviaround')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='GPTrivia.roundquestionanalysisrun')),
            ],
            options={
                'ordering': ['round_date', 'round_name', 'question_number', 'id'],
            },
        ),
    ]
