# Generated by Django 4.1.7 on 2026-03-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0027_alter_mergedpresentation_crowned_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptriviaround',
            name='source_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
