# Generated by Django 4.1.7 on 2026-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0028_gptriviaround_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='instruction_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='media_file',
            field=models.FileField(blank=True, default='', upload_to='round_analysis_media'),
        ),
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='media_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='media_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='source_slide_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundquestionanalysisentry',
            name='source_slide_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
