# Generated by Django 4.1.7 on 2026-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPTrivia', '0035_answersheetentry_grade_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedpresentation',
            name='crowned_winner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mergedpresentation',
            name='host',
            field=models.CharField(default='Alex', max_length=100),
        ),
        migrations.AlterField(
            model_name='mergedpresentation',
            name='scorekeeper',
            field=models.CharField(default='Alex', max_length=100),
        ),
    ]
