name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # This step sets up known_hosts to avoid SSH host verification prompts
      - name: Set up SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan hailsciencetrivia.com >> ~/.ssh/known_hosts

      # This step SSH into the server and executes the commands
      - name: Deploy to Server
        run: |
          echo "Creating ssh folder..."
          mkdir -p ~/.ssh
          echo "Adding deploy key..."
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          echo "Setting permissions..."
          chmod 700 ~/.ssh/deploy_key
          echo "Adding server to known hosts..."
          /usr/bin/ssh-keyscan hailsciencetrivia.com >> ~/.ssh/known_hosts 2>&1
          echo "Deploying to server..."
          ssh -i ~/.ssh/deploy_key rawr@hailsciencetrivia.com << EOF
            set -x
            echo "Changing directories..."
            cd ~/git/GPTrivia
            echo "Pulling from GitHub..."
            git pull --no-edit
            echo "Stopping uvicorn..."
            pkill -f 'uvicorn GPTrivia.asgi:application'
            MAX_WAIT=10
            while pgrep -f 'uvicorn GPTrivia.asgi:application' > /dev/null; do
                if [ "$MAX_WAIT" -le 0 ]; then
                    echo "Uvicorn did not stop in time. Proceeding with force kill."
                    pkill -9 -f 'uvicorn GPTrivia.asgi:application'
                    break
                fi
                echo "Waiting for Uvicorn to stop..."
                sleep 1
                ((MAX_WAIT--))
            done
            echo "Starting uvicorn..."
            uvicorn GPTrivia.asgi:application --reload
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
