name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # This step sets up known_hosts to avoid SSH host verification prompts
      - name: Set up SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan hailsciencetrivia.com >> ~/.ssh/known_hosts

      # This step SSH into the server and executes the commands
      - name: Deploy to Server
        run: |
          echo "Creating ssh folder..."
          mkdir -p ~/.ssh
          echo "Adding deploy key..."
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          echo "Setting permissions..."
          chmod 600 ~/.ssh/deploy_key
          echo "Adding server to known hosts..."
          ssh-keyscan hailsciencetrivia.com >> ~/.ssh/known_hosts
          echo "Deploying to server..."
          ssh -i ~/.ssh/deploy_key rawr@hailsciencetrivia.com << EOF
            echo "Changing directories..."
            cd ~/git/GPTrivia
            echo "Pulling from GitHub..."
            git pull --no-edit
            echo "Stopping uvicorn..."
            pkill -f 'uvicorn GPTrivia.asgi:application'
            echo "Starting uvicorn..."
            nohup uvicorn GPTrivia.asgi:application --reload > uvicorn.log 2>&1 &
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
